### PR TITLE
mysql: add toppings to pizza and format prices

### PR DESCRIPTION
**Pull request by n0v1c3**

### CODE REVIEW

**Comment by n0v1c3** [comment]
If you see this the old "menu" table can be dropped as it is no longer in use.

**Comment by n0v1c3** [comment]
Don't forget the "pull" on your test server.

**Comment by zhaaltoc** [comment]
pulling in updates

**Comment by zhaaltoc** [comment]
ok.  tesg.deminicos.ca:81 is operational now..

**Pull request merged**
